version: '3'
services:
  spring-boot-demo:
    build: .
    image: spring-boot-demo
    restart: always
    ports:
      - 8082:8082

  elk:
    build: ./elk
    image: spring-boot-demo-elk
    ports:
      - 5601:5601